### ISSUE TITLE
h2online crashes if don't run as administrator

### ISSUE THREAD

**Issue by shayaantx** [FishPhd/H2V-Online-Launcher#12]
Hi, nice project, I ran the h2online as an admin on windows (prior to this I did not run as an admin, even though my windows user is an admin :|), all of the sudden h2online started crashing.

The error is below. Can there be a nicer error message for this, instead of the crashing? As it is not evident from the program crash what is going on, I only found out by debugging it myself.

{"Access to the path 'C:\Program Files (x86)\Microsoft Games\Halo 2\h2vlauncher.log' is denied."}

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at h2online.MainWindow.InitiateTrace() in E:\projects\H2V-Online-Launcher-master\H2V\MainWindow.xaml.cs:line 63
   at h2online.MainWindow..ctor() in E:\projects\H2V-Online-Launcher-master\H2V\MainWindow.xaml.cs:line 39

**Comment by pnill** [comment]
This is expected behavior as it doesn't have an exception handler if it's unable to access the log file which is restricted to Administrators.

**Comment by iSupersniper** [comment]
The latest version automatically asks you to run the program as the administrator.  This should no longer be a problem.
